//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserClient.WcfHalfServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfHalfServices.IHalfService")]
    public interface IHalfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHalfService/GetData", ReplyAction="http://tempuri.org/IHalfService/GetDataResponse")]
        string GetData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHalfServiceChannel : UserClient.WcfHalfServices.IHalfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HalfServiceClient : System.ServiceModel.ClientBase<UserClient.WcfHalfServices.IHalfService>, UserClient.WcfHalfServices.IHalfService {
        
        public HalfServiceClient() {
        }
        
        public HalfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HalfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HalfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HalfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
    }
}
