CREATE TABLE [dbo].[Seed](
	[ID] [int] NOT NULL,
	[Value] [int] NOT NULL,
	[Memo] [varchar](50) NULL,
 CONSTRAINT [PK_Seed] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF