//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.hooyes.lms.LMSMonitor.SMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMS.SendMessageSoap")]
    public interface SendMessageSoap {
        
        // CODEGEN: Generating message contract since message sendmsgRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.hooyes.lms.LMSMonitor.SMS.sendmsgResponse sendmsg(com.hooyes.lms.LMSMonitor.SMS.sendmsgRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MySoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendmsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendmsgRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public com.hooyes.lms.LMSMonitor.SMS.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string mobileNO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msgsender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string aid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string msgcontent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sendtype;
        
        public sendmsgRequest() {
        }
        
        public sendmsgRequest(com.hooyes.lms.LMSMonitor.SMS.MySoapHeader MySoapHeader, string mobileNO, string msgsender, string aid, string msgcontent, string sendtype) {
            this.MySoapHeader = MySoapHeader;
            this.mobileNO = mobileNO;
            this.msgsender = msgsender;
            this.aid = aid;
            this.msgcontent = msgcontent;
            this.sendtype = sendtype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendmsgResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendmsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sendmsgResult;
        
        public sendmsgResponse() {
        }
        
        public sendmsgResponse(string sendmsgResult) {
            this.sendmsgResult = sendmsgResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendMessageSoapChannel : com.hooyes.lms.LMSMonitor.SMS.SendMessageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMessageSoapClient : System.ServiceModel.ClientBase<com.hooyes.lms.LMSMonitor.SMS.SendMessageSoap>, com.hooyes.lms.LMSMonitor.SMS.SendMessageSoap {
        
        public SendMessageSoapClient() {
        }
        
        public SendMessageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMessageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.hooyes.lms.LMSMonitor.SMS.sendmsgResponse com.hooyes.lms.LMSMonitor.SMS.SendMessageSoap.sendmsg(com.hooyes.lms.LMSMonitor.SMS.sendmsgRequest request) {
            return base.Channel.sendmsg(request);
        }
        
        public string sendmsg(com.hooyes.lms.LMSMonitor.SMS.MySoapHeader MySoapHeader, string mobileNO, string msgsender, string aid, string msgcontent, string sendtype) {
            com.hooyes.lms.LMSMonitor.SMS.sendmsgRequest inValue = new com.hooyes.lms.LMSMonitor.SMS.sendmsgRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.mobileNO = mobileNO;
            inValue.msgsender = msgsender;
            inValue.aid = aid;
            inValue.msgcontent = msgcontent;
            inValue.sendtype = sendtype;
            com.hooyes.lms.LMSMonitor.SMS.sendmsgResponse retVal = ((com.hooyes.lms.LMSMonitor.SMS.SendMessageSoap)(this)).sendmsg(inValue);
            return retVal.sendmsgResult;
        }
    }
}
