-- =============================================
-- Version:     1.0.0.1
-- Author:		hooyes
-- Create date: 2013-09-19
-- Update date: 2013-09-19
-- Desc:
-- =============================================
CREATE PROCEDURE [dbo].[Update_GatewayLog]
    @MerId VARCHAR(20) = NULL ,
    @BusiId VARCHAR(10) = NULL ,
    @OrdId VARCHAR(20) = NULL ,
    @OrdAmt VARCHAR(15) = NULL ,
    @Version VARCHAR(10) = NULL ,
    @BgRetUrl VARCHAR(100) = NULL ,
    @PageRetUrl VARCHAR(100) = NULL ,
    @GateId DECIMAL(18, 0) = NULL ,
    @Param1 NVARCHAR(100) = NULL ,
    @Param2 NVARCHAR(100) = NULL ,
    @Param3 NVARCHAR(100) = NULL ,
    @Param4 NVARCHAR(100) = NULL ,
    @Param5 NVARCHAR(100) = NULL ,
    @Param6 NVARCHAR(100) = NULL ,
    @Param7 NVARCHAR(100) = NULL ,
    @Param8 NVARCHAR(100) = NULL ,
    @Param9 NVARCHAR(100) = NULL ,
    @Param10 NVARCHAR(100) = NULL ,
    @OrdDesc NVARCHAR(256) = NULL ,
    @ShareType VARCHAR(10) = NULL ,
    @ShareData NVARCHAR(100) = NULL ,
    @Priv1 NVARCHAR(60) = NULL ,
    @CustomIp VARCHAR(60) = NULL ,
    @ChkValue VARCHAR(256) = NULL ,
    @Plain VARCHAR(256) = NULL ,
    @PayStat VARCHAR(10) = NULL ,
    @PayTime VARCHAR(20) = NULL ,
    @Flag VARCHAR(10) = NULL
AS 
    INSERT  INTO [GatewayLog]
            ( [MerId] ,
              [BusiId] ,
              [OrdId] ,
              [OrdAmt] ,
              [Version] ,
              [BgRetUrl] ,
              [PageRetUrl] ,
              [GateId] ,
              [Param1] ,
              [Param2] ,
              [Param3] ,
              [Param4] ,
              [Param5] ,
              [Param6] ,
              [Param7] ,
              [Param8] ,
              [Param9] ,
              [Param10] ,
              [OrdDesc] ,
              [ShareType] ,
              [ShareData] ,
              [Priv1] ,
              [CustomIp] ,
              [ChkValue] ,
              [Plain] ,
              [PayStat] ,
              [PayTime] ,
              [Flag] ,
              [CreateDate]
            )
    VALUES  ( @MerId ,
              @BusiId ,
              @OrdId ,
              @OrdAmt ,
              @Version ,
              @BgRetUrl ,
              @PageRetUrl ,
              @GateId ,
              @Param1 ,
              @Param2 ,
              @Param3 ,
              @Param4 ,
              @Param5 ,
              @Param6 ,
              @Param7 ,
              @Param8 ,
              @Param9 ,
              @Param10 ,
              @OrdDesc ,
              @ShareType ,
              @ShareData ,
              @Priv1 ,
              @CustomIp ,
              @ChkValue ,
              @Plain ,
              @PayStat ,
              @PayTime ,
              @Flag ,
              GETDATE()
            )
  
    RETURN 0
