<?php
$webdb['auto_userpostpic']='1';
$webdb['myLinks']='';
$webdb['postresumeMaxDay']='7';
$webdb['module_pre']='business';
$webdb['usersRresumeMax']='10';
$webdb['zhaopin_listnum']='20';
$webdb['resumeView_contact']='0';
$webdb['iconMaxUserPostResume']='50';
$webdb['usersJobsMax']='20';
$webdb['checkUserPostResume']='1';
$webdb['checkUserPostJob']='1';
$webdb['allowUserPostJob']='1';
$webdb['allowGuestComment']='1';
$webdb['module_id']='127';
$webdb['allowGuestCommentPass']='1';
$webdb['forbidComment']='0';
$webdb['search_left']='';
$webdb['search_right']='';
$webdb['vendorRenzheng']='0';
$webdb['renzheng3doc']='年销售报表 现行营销方案 企业组织架构';
$webdb['info_bd_picnum']='6';
$webdb['vipselfdomaincannot']='www,business,gt115,gt';
$webdb['vipselfdomain']='1';
$webdb['vip_par_payfor']='1';
$webdb['vip_min_long']='1';
$webdb['company_uploadsize_max']='100';
$webdb['company_upload_max']='8';
$webdb['company_uploadnum_max']='100';
$webdb['company_picsort_Max']='10';
$webdb['homepage_banner_size']='80';
$webdb['homepage_ico_size']='50';
$webdb['post_add_money']='10';
$webdb['company_add_money']='100';
$webdb['autoyz_tg']='1';
$webdb['tg_permoney']='1';
$webdb['company_news_shownum']='10';
$webdb['renzheng_infonum']='10';
$webdb['bencandyIsHtml']='0';
$webdb['bencandyFormatHtml']='b/html/{$fid}-{$id}.htm';
$webdb['company_lxfs']='1';
$webdb['maxMysort']='10';
$webdb['postcompanyauto_yz']='1';
$webdb['freeSentform2']='20';
$webdb['freeSentform1']='5';
$webdb['postfileMaxSize']='500';
$webdb['post_danwei']='千克|顿|件|箱|只|支|盒|套';
$webdb['postauto_yz']='1';
$webdb['gqlist_cache_time']='0.01';
$webdb['InfoIndexRow']='8';
$webdb['InfoIndexLeng']='32';
$webdb['showposttimelast']='0';
$webdb['allNotice']='';
$webdb['hotline']='800-820-8888';
$webdb['viewHistoryNums']='10';
$webdb['Info_showsortnum']='16';
$webdb['kefuinfo']='电话：020-8888888
传真：020-8888889
邮箱：me@hooyes.com
Q Q：227046
MSN：hooyes@live.cn';
$webdb['InfoListRow']='10';
$webdb['InfoListLeng']='30';
$webdb['list_notice']='对于初次接触本网的商家，请在多做比较后，先发单询问，合则详谈；

推荐多打电话咨询，实地考察——以便成功达成供应和采购';
$webdb['member_style']='images';
$webdb['page_head_style']='2';
$webdb['listwidth']='full';
$webdb['business_style']='blue';
$webdb['Info_metakeywords_buy']='中国橡胶企业大全,中国橡胶企业名录大全,橡胶';
$webdb['Info_metakeywords_sale']='中国橡胶企业大全,中国橡胶企业名录大全,橡胶';
$webdb['Info_metakeywords']='中国橡胶企业大全,中国橡胶企业名录大全,橡胶';
$webdb['Info_webname']='中国橡胶企业大全';
$webdb['updateresumeMaxHour']='1';
$webdb['postzhCheck']='1';
$webdb['postzhDiyNum']='2';
$webdb['iconMaxUserPostZh']='50';
$webdb['zhListNum']='20';
 
?>