<?php
$db->query("ALTER TABLE `{$pre}hack` ADD `class1` VARCHAR( 30 ) NOT NULL ,ADD `class2` VARCHAR( 30 ) NOT NULL ");
$db->query("ALTER TABLE `{$pre}hack` ADD `list` VARCHAR( 10 ) NOT NULL");
$db->query("ALTER TABLE `{$pre}hack` ADD `linkname` TEXT NOT NULL");
$db->query("ALTER TABLE `{$pre}hack` ADD `isbiz` TINYINT( 1 ) NOT NULL");


$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('set_comsort_index', '网站首页设置', 0, '', '', '', '', '', 'index.php?lfj=channel&job=edit&id=1', '', 19, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('article_module', '网站内容模型管理', 0, '', '', '', 'admin/article_module.php\r\nadmin/article_module/', '', 'index.php?lfj=article_module&job=list', '', 14, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('form_module', '万能表单模型管理', 0, '', '', '', '/admin/form_module.php\r\n/admin/form_content.php\r\n/admin/template/form_content/\r\n/admin/template/form_module/\r\n/php168/form_tpl/\r\n/do/form.php\r\n/do/bencandy_form.php\r\n/do/list_form.php\r\n/member/form.php', '', 'index.php?lfj=form_module&job=list', '', 13, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('comment_set', '内容评论设置', 0, '', '', '', '/admin/comment.php', '', 'index.php?lfj=comment&job=set', '', 12, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('setmakeALLhtml_set', '网站静态页全局设置', 0, '', '', '', '', '', 'index.php?lfj=html&job=set', '', 11, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('module_list', '整合P8其它系统设置', 0, '', '', '', '', '', 'index.php?lfj=module&job=list', '', 10, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('blend_set', '整合外部论坛系统设置', 0, '', '', '', '', '', 'index.php?lfj=blend&job=set', '', 9, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('cache_cache', '更新缓存/数据修复', 0, '', '', '', '/admin/cache.php', '', 'index.php?lfj=cache&job=cache', '', 15, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('channel_list', '频道独立页管理', 0, '', '', '', '', '', 'index.php?lfj=channel&job=list', '', 6, '', 0, 'base', '网站常用功能管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('guestbook_list', '留言本管理', 0, '', '', '', 'admin/template/guestbook/\r\nadmin/guestbook.php\r\ndo/guestbook.php', '{$pre}guestbook', 'index.php?lfj=guestbook&job=list', '', 7, '', 0, 'base', '网站常用功能管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('vote_list', '投票系统', 0, '', '', '', '', '', 'index.php?lfj=vote&job=list', '', 5, '', 0, 'base', '网站常用功能管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('mysql_sql', '数据库管理', 0, '', '', '', '', '', 'index.php?lfj=mysql&job=sql', '', 6, '', 0, 'base', '数据库工具')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('artic_addpic', '快速发图', 0, '', '', '', '', '', 'index.php?lfj=artic&job=addpic', '', 4, '', 0, 'article', '内容/栏目/评论管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('company_list', '企业资料管理', 0, '', '', '', '', '', 'index.php?lfj=company&job=list', '', 8, '', 0, 'member', '用户管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('member_addmember', '添加新用户', 0, '', '', '', '', '', 'index.php?lfj=member&job=addmember', '', 6, '', 0, 'member', '用户管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('regfield', '用户资料字段管理', 0, '', '', '', '', '', 'index.php?lfj=regfield&job=editsort', '', 7, '', 0, 'member', '用户管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('report_list', '内容好坏举报管理', 0, '', '', '', '', '', 'index.php?lfj=report&job=list', '', 8, '', 0, 'other', '内容模型插件功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('limitword_replace', '字符替换', 0, '', '', '', '', '', 'index.php?lfj=limitword&job=replace', '', 6, '', 0, 'other', '内容模型插件功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('copyfrom_list', '来源地址管理', 0, '', '', '', '', '', 'index.php?lfj=copyfrom&job=list', '', 7, '', 0, 'other', '内容模型插件功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('googlemap_makemap', '百度新闻协议/google协议', 0, '', '', '', '', '', 'index.php?lfj=googlemap&job=makemap', '', 3, '', 0, 'other', '内容模型插件功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('ad_listAdPlace', '普通广告位管理', 0, '', '', '', '', '', 'index.php?lfj=ad&job=listad', '', 9, '', 0, 'other', '广告模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('ad_listuserad', '普通广告销售管理', 0, '', '', '', '', '', 'index.php?lfj=ad&job=listuserad', '', 8, '', 0, 'other', '广告模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('sellad', '竞价广告位管理', 0, '', '', '', '', '', 'index.php?lfj=sellad&job=listad', '', 7, '', 0, 'other', '广告模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('sellad_listuser', '竞价广告销售管理', 0, '', '', '', '', '', 'index.php?lfj=sellad&job=listuser', '', 6, '', 0, 'other', '广告模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('alipay_set', '在线充值支付管理', 0, '', '', '', '', '', 'index.php?lfj=alipay&job=list', '', 9, '', 0, 'other', '电子商务管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('shoporder', '商城订单管理', 0, '', '', '', '', '', 'index.php?lfj=shoporder&job=list', '', 8, '', 0, 'other', '电子商务管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('template_list', '模板设置', 0, '', '', '', '', '', 'index.php?lfj=template&job=list', '', 1, '', 0, 'other', '风格/模板设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('style_editstyle', '风格管理', 0, '', '', '', '', '', 'index.php?lfj=style&job=edittpl', '', 2, '', 0, 'other', '风格/模板设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('exam_sort', '问卷分类管理', 0, '', '', '', '', '', 'index.php?lfj=exam_sort&job=listsort', '', 4, '', 0, 'other', '问卷调查模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('exam_title', '问卷题库管理', 0, '', '', '', '', '', 'index.php?lfj=exam_sort&job=listsort', '', 3, '', 0, 'other', '问卷调查模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('exam_form', '问卷表单管理', 0, '', '', '', '', '', 'index.php?lfj=exam_form&job=list', '', 2, '', 0, 'other', '问卷调查模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('exam_read', '问卷表单批阅', 0, '', '', '', '', '', 'index.php?lfj=exam_read&job=list', '', 1, '', 0, 'other', '问卷调查模块')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('gather_copysina', '新浪新闻采集', 0, '', '', '', '', '', 'index.php?lfj=gather&job=copysina', '', 3, '', 0, 'other', '数据采集器')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('gather_list', '采集规则管理', 0, '', '', '', '', '', 'index.php?lfj=gather&job=list', '', 2, '', 0, 'other', '数据采集器')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('gather_list_sort', '采集规则分类管理', 0, '', '', '', '', '', 'index.php?lfj=gather_sort&job=list', '', 1, '', 0, 'other', '数据采集器')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('js_list', 'JS内容调用', 0, '', '', '', '', '', 'index.php?lfj=js&job=list', '', 9, '', 0, 'other', '其它功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('propagandize_list', '推广赚取积分功能', 0, '', '', '', '', '', 'index.php?lfj=propagandize&job=list', '', 8, '', 0, 'other', '其它功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('jfadmin_mod', '积分介绍管理', 0, '', '', '', '', '', 'index.php?lfj=jfadmin&job=listjf', '', 7, '', 0, 'other', '其它功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('attachment_list', '附件管理', 0, '', '', '', '', '', 'index.php?lfj=attachment&job=list', '', 6, '', 0, 'other', '其它功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('area_list', '地区管理', 0, '', '', '', '', '', 'index.php?lfj=area&job=list', '', 5, '', 0, 'other', '其它功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('upgrade_ol', '系统在线升级', 0, '', '', '', '', '', 'index.php?lfj=upgrade&job=get', '', 4, '', 0, 'other', '其它功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('mail_send', '邮件群发', 0, '', '', '', '', '', 'index.php?lfj=mail&job=send', '', 2, '', 0, 'other', '消息/邮件群发')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('message_send', '站内消息群发', 0, '', '', '', '', '', 'index.php?lfj=message&job=send', '', 3, '', 0, 'other', '消息/邮件群发')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('sms_send', '手机短信群发', 0, '', '', '', '', '', 'index.php?lfj=sms&job=send', '', 1, '', 0, 'other', '消息/邮件群发')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('code_code', 'PHPWIND营销模块', 0, '', '', '', '', '', 'index.php?lfj=code&job=code', '', 2, '', 0, 'other', '站外功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('cnzz_set', 'CNZZ流量统计', 0, '', '', '', '', '', 'index.php?lfj=cnzz&job=ask', '', 3, '', 0, 'other', '站外功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('center_config', '网站全局参数设置', 0, '', '', '', '/admin/template/center/config.htm', '', 'index.php?lfj=center&job=config', '', 20, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('article_more_config', '内容模型基本设置', 0, '', '', '', '/admin/article_more.php', '', 'index.php?lfj=article_more&job=config', '', 16, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('hack_list', '插件管理中心', 0, '', '', '', '/admin/hack.php\r\n/admin/template/hack/list.htm', '', 'index.php?lfj=hack&job=list', '', 8, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('menu_list', '网站头部导航菜单设置', 0, '', '', '', '', '', 'index.php?lfj=guidemenu&job=list', '', 5, '', 0, 'base', '菜单管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('adminmenu_list', '管理员后台菜单设置', 0, '', '', '', '', '', 'index.php?lfj=adminguidemenu&job=list', '', 4, '', 0, 'base', '菜单管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('membermenu_list', '会员中心菜单设置', 0, '', '', '', '', '', 'index.php?lfj=memberguidemenu&job=list', '', 3, '', 0, 'base', '菜单管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('alonepage_list', '单篇文章独立页面管理', 0, '', '', '', '', '', 'index.php?lfj=alonepage&job=list', '', 8, '', 0, 'base', '网站常用功能管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('friendlink_mod', '友情链接管理', 0, '', '', '', '', '', 'index.php?lfj=friendlink&job=list', '', 9, '', 0, 'base', '网站常用功能管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('mysql_out', '备份数据库', 0, '', '', '', '', '', 'index.php?lfj=mysql&job=out', '', 9, '', 0, 'base', '数据库工具')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('mysql_into', '数据库还原', 0, '', '', '', '', '', 'index.php?lfj=mysql&job=into', '', 8, '', 0, 'base', '数据库工具')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('mysql_del', '删除备份数据', 0, '', '', '', '', '', 'index.php?lfj=mysql&job=del', '', 7, '', 0, 'base', '数据库工具')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('sort_listsort', '栏目管理', 0, '', '', '', '', '', 'index.php?lfj=sort&job=listsort&only=&mid=', '', 9, '</a><A HREF=\'index.php?lfj=sort&job=listsort&only=&mid=\' target=main>栏目管理</A> | <A HREF=\'index.php?lfj=sort&job=addsort&only=&mid=\' target=main>创建栏目</A> <a>', 0, 'article', '内容/栏目/评论管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('artic_listartic', '内容管理', 0, '', '', '', '', '', 'index.php?lfj=artic&job=listartic&only=1&mid=', '', 8, '内容管理<font color=#959595>(修改、删除等)</font>', 0, 'article', '内容/栏目/评论管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('comment_list', '评论管理', 0, '', '', '', '', '', 'index.php?lfj=comment&job=list', '', 7, '', 0, 'article', '内容/栏目/评论管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('form_content', '万能表单内容管理', 0, '', '', '', '', '', 'index.php?lfj=form_content&job=list', '', 6, '', 0, 'article', '内容/栏目/评论管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('artic_postnew', '发表文章', 0, '', '', '', '', '', 'index.php?lfj=post&job=postnew&only=1&mid=', '', 5, '发表<font color=#959595>(文章、图片等)</font>', 0, 'article', '内容/栏目/评论管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('index_label', '首页标签设置', 0, '', '', '', '', '', '../index.php?&ch=1&chtype=0&jobs=show', '', 4, '', 0, 'article', '更新标签内容')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('s_list_fid', '栏目/内容页标签设置', 0, '', '', '', '', '', 'index.php?lfj=channel&job=list_fid', '', 3, '', 0, 'article', '更新标签内容')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('up_splist_fid', '专题页标签设置', 0, '', '', '', '', '', 'index.php?lfj=special&job=list&onlyshow=label', '', 2, '', 0, 'article', '更新标签内容')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('makeindexhtml_make', '主页静态', 0, '', '', '', '', '', '../index.php?&ch=1&MakeIndex=1', '', 5, '</a><a href=\'../index.php?&ch=1&MakeIndex=1\' target=\'_blank\' onclick=\\\"return confirm(\'你确实要把首页生成静态吗?生成静态后,如有更改其它相关设置,需要重新点击生成一次静态.才可以看到效果.\')\");\\\">主页静态</a> | <A HREF=\'index.php?lfj=center&job=delindex\' target=main>删除</A><a>', 0, 'article', '静态页生成管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('makehtml_make', '栏目内容静态页管理', 0, '', '', '', '', '', 'index.php?lfj=html&job=list', '', 4, '', 0, 'article', '静态页生成管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('spmakehtml_make', '专题静态页管理', 0, '', '', '', '', '', 'index.php?lfj=html&job=listsp', '', 3, '', 0, 'article', '静态页生成管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('setmakehtml_set', '静态网页样式设置', 0, '', '', '', '', '', 'index.php?lfj=html&job=set', '', 2, '', 0, 'article', '静态页生成管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('special_list', '专题管理', 0, '', '', '', '', '', 'index.php?lfj=special&job=list', '', 2, '', 0, 'article', '专题管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('spsort_listsort', '专题分类管理', 0, '', '', '', '', '', 'index.php?lfj=spsort&job=listsort', '', 1, '', 0, 'article', '专题管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('member_list', '用户资料管理', 0, '', '', '', '', '', 'index.php?lfj=member&job=list', '', 9, '', 0, 'member', '用户管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('article_group_config', '内容模型权限设置', 0, '', '', '', '', '', 'index.php?lfj=article_group&job=list', '', 6, '', 0, 'member', '权限管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('group_list', '前台权限管理', 0, '', '', '', '', '', 'index.php?lfj=group&job=list', '', 5, '', 0, 'member', '权限管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('group_list_admin', '后台权限管理', 0, '', '', '', '', '', 'index.php?lfj=group&job=list_admin', '', 4, '', 0, 'member', '权限管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('group_add', '添加用户组', 0, '', '', '', '', '', 'index.php?lfj=group&job=add', '', 3, '', 0, 'member', '权限管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('getkeyword_do', '关键字管理', 0, '', '', '', '', '', 'index.php?lfj=getkeyword&job=list', '', 4, '</a><A HREF=\'index.php?lfj=getkeyword&job=list\' target=\'main\'>关键字管理</A> | <A HREF=\'index.php?lfj=getkeyword&job=get\' target=\'main\'>提取关键字</A><a>', 0, 'other', '内容模型插件功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('limitword_list', '不良词语过滤', 0, '', '', '', '', '', 'index.php?lfj=limitword&job=list', '', 9, '', 0, 'other', '内容模型插件功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('article_more_avoidgather', '防采集设置', 0, '', '', '', '', '', 'index.php?lfj=article_more&job=avoidgather', '', 5, '', 1, 'other', '内容模型插件功能')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('moneycard_make', '点卡充值管理', 0, '', '', '', '', '', 'index.php?lfj=moneycard&job=make', '', 7, '', 1, 'other', '电子商务管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('logs_login_logs', '后台登录日志', 0, '', '', '', '', '', 'index.php?lfj=logs&job=login_logs', '', 2, '', 0, 'other', '日志管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('logs_admin_do_logs', '后台操作日志', 0, '', '', '', '', '', 'index.php?lfj=logs&job=admin_logs', '', 1, '', 0, 'other', '日志管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('user_reg', '会员注册设置', 0, '', '', '', '/admin/template/center/user_reg.htm', '', 'index.php?lfj=center&job=user_reg', '', 18, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('center_cache', '高速缓存设置', 0, '', '', '', '/admin/template/center/cache.htm', '', 'index.php?lfj=center&job=cache', '', 17, '', 0, 'base', '核心设置')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('fu_sort_power', '辅栏目管理', 0, '', '', '', '', '', 'index.php?lfj=fu_sort&job=listsort', '', 0, '', 0, 'article', '辅栏目管理')");
$db->query("INSERT INTO `{$pre}hack` (`keywords`, `name`, `isclose`, `author`, `config`, `htmlcode`, `hackfile`, `hacksqltable`, `adminurl`, `about`, `list`, `linkname`, `isbiz`, `class1`, `class2`) VALUES ('fu_artic_power', '辅栏目内容管理', 0, '', '', '', '', '', 'index.php?lfj=fu_artic&job=listartic', '', 0, '', 0, 'article', '辅栏目管理')");

write_hackmenu_cache();
function write_hackmenu_cache(){
	global $db,$pre;
	$show="<?php\r\n";
	$query = $db->query("SELECT * FROM {$pre}hack ORDER BY list DESC");
	while($rs = $db->fetch_array($query)){
		if(!$rs[adminurl]||!$rs[class2]||!$rs[class1]){
			continue;
		}
		$rs[adminurl]=addslashes($rs[adminurl]);
		$rs[linkname] && $rs[name]=$rs[linkname];
		$rs[name]=addslashes($rs[name]);
		$s="\r\n\$menu_partDB['{$rs[class1]}'][]='{$rs[class2]}';\r\n\$menudb['{$rs[class2]}']['{$rs[name]}']=array('power'=>'{$rs[keywords]}','link'=>'{$rs[adminurl]}');\r\n";
		if($rs[isbiz]){
			$show.="\r\nif(\$IS_BIZPhp168||\$GLOBALS[IS_BIZPhp168]){".$s."}\r\n";
		}else{
			$show.=$s;
		}
	}
	write_file(PHP168_PATH."php168/hack.php",$show.'?>');
}

?>