/* data */
var menu = [
   { enable: true, vMenu: "Market", vSubMenu: ['Sales Report', 'Bank Card Report', 'Cancellation Report', 'CC Trans Log', 'Plan Renew/Change', 'Reward Report', 'inDirect Sales Report', 'Hanyastar Report manage', 'Survey', 'Market Refund', 'AU Post Pay', 'Promotion Code', 'Ticket Report', 'NXX Request', 'Sales Rep Manage', 'TW DID Report', 'Profitablity & Usage Report', 'Ads Manage', 'Save Option Manage', 'Cancel Rate'] }
   , { enable: false, vMenu: "Sales|Signup", vSubMenu: ['US BB', 'US HK', 'US-TW', 'US-DM', 'AU BB', 'AU Star BB', 'AU DSL', 'SG BB', 'iTalkLite CA', 'iTalkLite US', 'CA BB', 'Tai Seng', 'AU Plan Dealer Support Only', 'Pop Out Window', 'CA HK', 'Delivery', 'US-KR BB', 'US-KR JA BB', 'CA-KR BB', 'CA-KR JA BB', 'US IFD per minute', 'CA IFD', 'INT BB', 'US Hanya Signup', 'CA Hanya Signup', 'PA-IN', 'KR DAILY', 'Sales Inbound Register', 'SalesInboundReport', 'Call Report', 'Pre Signup Report', 'Customer Request Info'] }
   , { enable: true, vMenu: "Dealer System", vSubMenu: ['Dealer Search', 'Manage Commission', 'Commission Request', 'Inventory Order', 'Customer Search', 'Dealer Approve', 'Dealer Donate', 'Customer Move Log', 'Dealer Report', 'Dealer Pre Signup Report', 'CHEQUE LIST', 'Top Up History Query', 'BB Credit Sign Up Payment Report', 'Transaction Report', 'Product Plan', 'Dealer Sales Cost', 'call quality feedback', 'Churn Rate Report', 'Adv Dealer Search', 'Box Installation Order', 'Check Repeat Register', 'Demo Plan Report'] }
   , { enable: true, vMenu: "Customer Support", vSubMenu: ['Call Rep', 'Ticket Batch Job', 'Trouble Tickets', 'Call Notes', 'Shipping/Handling', 'Customer Mail', 'PORT IN CHECK', 'Repeat Cancellation Report', 'Bible Adm', 'System Account', '新加坡GIRO管理员', 'Hanya CRM', 'Customer Report', 'CreditCard Expiration Report', 'Negative Balance', 'DemoAccount Manage', 'Outbound Commission', 'SG Customer Manage', 'Satisfaction Report'] }
   , { enable: true, vMenu: "Port-In PSTNs", vSubMenu: ['Search/Upload Requests', 'CA CSV update Requests', 'US CSV update Requests', 'Export Requests', 'Monthly export Requests', 'Weekly Report', 'AU Change Status', 'ExportELoa'] }
   , { enable: true, vMenu: "Visit/Cancellation", vSubMenu: ['Visit Back Rep', 'Visit Back Admin', 'Cancel Rep', 'Cancel Report', 'Cancel Refund Report', 'Cancel Rep Manage'] }
   , { enable: true, vMenu: "System", vSubMenu: ['911 Report', 'Web Stats', 'Audit Report', 'Technical Service Bulletin', 'Inventory', 'iTalkDID'] }
   , { enable: true, vMenu: "NOC", vSubMenu: ['Category Edit', 'Noc Tickets', 'Noc Ticket Report', 'System Issue', 'Routing Change', 'Traffic Report', 'WIKI', 'Web Monitor', 'Account Manual Block', 'Server Monitor'] }
   ]