//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.hooyes.app.AngryApple.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="M1", Namespace="http://schemas.datacontract.org/2004/07/com.hooyes.lms.Svc.Model")]
    [System.SerializableAttribute()]
    public partial class M1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tstampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCard {
            get {
                return this.IDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardField, value) != true)) {
                    this.IDCardField = value;
                    this.RaisePropertyChanged("IDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDSN {
            get {
                return this.IDSNField;
            }
            set {
                if ((object.ReferenceEquals(this.IDSNField, value) != true)) {
                    this.IDSNField = value;
                    this.RaisePropertyChanged("IDSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SN {
            get {
                return this.SNField;
            }
            set {
                if ((this.SNField.Equals(value) != true)) {
                    this.SNField = value;
                    this.RaisePropertyChanged("SN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                if ((this.flagField.Equals(value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sID {
            get {
                return this.sIDField;
            }
            set {
                if ((this.sIDField.Equals(value) != true)) {
                    this.sIDField = value;
                    this.RaisePropertyChanged("sID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sType {
            get {
                return this.sTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sTypeField, value) != true)) {
                    this.sTypeField = value;
                    this.RaisePropertyChanged("sType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tag {
            get {
                return this.tagField;
            }
            set {
                if ((this.tagField.Equals(value) != true)) {
                    this.tagField = value;
                    this.RaisePropertyChanged("tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tstamp {
            get {
                return this.tstampField;
            }
            set {
                if ((object.ReferenceEquals(this.tstampField, value) != true)) {
                    this.tstampField = value;
                    this.RaisePropertyChanged("tstamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="R", Namespace="http://schemas.datacontract.org/2004/07/com.hooyes.lms.Svc.Model")]
    [System.SerializableAttribute()]
    public partial class R : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SN {
            get {
                return this.SNField;
            }
            set {
                if ((this.SNField.Equals(value) != true)) {
                    this.SNField = value;
                    this.RaisePropertyChanged("SN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/I", ReplyAction="http://tempuri.org/IService1/IResponse")]
        com.hooyes.app.AngryApple.SR.R I(com.hooyes.app.AngryApple.SR.M1 mc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/V", ReplyAction="http://tempuri.org/IService1/VResponse")]
        com.hooyes.app.AngryApple.SR.R V(string k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : com.hooyes.app.AngryApple.SR.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<com.hooyes.app.AngryApple.SR.IService1>, com.hooyes.app.AngryApple.SR.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public com.hooyes.app.AngryApple.SR.R I(com.hooyes.app.AngryApple.SR.M1 mc) {
            return base.Channel.I(mc);
        }
        
        public com.hooyes.app.AngryApple.SR.R V(string k) {
            return base.Channel.V(k);
        }
    }
}
