CREATE TABLE [dbo].[MSessions](
	[MID] [int] NOT NULL,
	[SessionId] [nvarchar](88) NULL,
	[IP] [varchar](50) NULL,
	[Created] [datetime] NULL,
 CONSTRAINT [PK_MSessions] PRIMARY KEY CLUSTERED 
(
	[MID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]